version: '3.4'
services:
   jupyter:
      build:
        context: ./nba_classifier
        network: host
      container_name: jupyter_nba_classifier
      restart: always
      user: '0'
      ports:
         - '8891:8888'
      volumes:
         - ./nba_classifier:/home/jovyan/work